<?php
// This file generated by Propel 1.7.1 convert-conf target
// from XML runtime conf file C:\xampp\htdocs\migrationstreams\build\propel\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'migrationstreams' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=migrationstreams',
        'user' => 'root',
        'password' => '',
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
        'options' => 
        array (
          'MYSQL_ATTR_INIT_COMMAND' => 
          array (
            'value' => 'SET NAMES utf8 COLLATE utf8_general_ci',
          ),
        ),
      ),
    ),
    'default' => 'migrationstreams',
  ),
  'generator_version' => '1.7.1',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-migrationstreams-conf.php');
return $conf;